language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "npm install"
  - "sudo npm install -g grunt-cli"
# command to run tests
script: make test
